### ISSUE TITLE
DLL Memory Hack on Windows 11

### ISSUE THREAD

**Issue by rttomlinson** [GameHackingAcademy/gamehackingacademy.github.io#3]
Hi, 
I'm going through DLL Memory Hack on Windows 11 and am currently stuck on getting the dll to inject when I boot up Wesnoth. https://gamehacking.academy/pages/3/03/. I can confirm that "Secure Boot State" is "Off" and BIOS mode is "UEFI". I tried setting `RequireSignedAppInit_DLLs` to 0 as suggested in https://stackoverflow.com/questions/75678722/appinit-dlls-and-loadappinit-dlls-not-working-on-windows-11-despite-disabling-se. Then I tried manually registering the dll using `regsvr32` and I get a "...dll was loaded but the entry-point DllRegisterServer was not found". What's interesting is that I can see my debug logs in `DebugView` so I suppose that is a little bit of an indication that _something_ is running. I'm at a bit of a loss where to go next. I tried looking up the missing DllRegisterServer error but did not anything too helpful. I'm considering looking at the other dll injector tools, maybe? Any direction would be immensely helpful and I've really been enjoying the curriculum. If there's a Discord or anything you could point me to, that would be appreciated as well. Thanks!

**Comment by attilathedud** [comment]
Another user made a comment calling out this same issue. It appears that Win11 x64 has some restrictions about injecting into x32 processes and AppInit_DLLs doesn't work anymore. I'll make a note in the lesson that the technique only works on Win10 and below.

In future lessons, it covers how to make a DLL injector, which sidesteps this issue entirely.
